### ISSUE TITLE
Maybe use the ClasspathSuite to write build.xml after running all tests

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/pizza-delivery#1]
See: https://github.com/takari/takari-cpsuite

This would allow to fix the overall status problem described here: https://github.com/scenarioo/pizza-delivery/blob/gh-pages/test/src/test/java/org/scenarioo/pizza/webtests/BranchAndBuildFileWriterTest.java

Another alternative would be to write branch.xml and build.xml in the gradle script in the test target.

**Comment by ideco** [comment]
Solved by initializing the folders in a static method at startup.

comment by @bruderol: I looked at it with Ivo and think that the current solution if perfect for the sample, no need to make it more complex.

@adiherzog feel free to reopen if you think this needs to be improved.

**Comment by adiherzog** [comment]
@ideco @bruderol Looks good to me. Thanks for the improvement.
