### ISSUE TITLE
Windows Setup section in README

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/pizza-delivery#13]
This section was added by @danielsuter and explains how the Scenarioo Viewer can be set up on Windows. I think this does not belong into the example but should be integrated into the general setup instructions of Scenarioo.

@bruderol @danielsuter What's your opinion on this?

PS: The last three lines are about running the example tests. I moved this to the top of the readme in branch https://github.com/scenarioo/pizza-delivery/tree/rename-pizza-shop-folder.

**Comment by bruderol** [comment]
@adiherzog totaly agree - this does not belong here - the link to the viewer setup docu should be sufficient - this will outdate here anyway and will be wrong after next release!

**Comment by bruderol** [comment]
if this is done, please check also whether we can close #10 - which both addresses same problem with different proposed solutions ;-)

**Comment by bruderol** [comment]
I think this can be closed??
