### ISSUE TITLE
Migrate Pizza Sample to JUnit 5

### ISSUE THREAD

**Issue by bruderol** [scenarioo/pizza-delivery#17]
sitting at Devoxx talk by the JUnit guys about Junit I realize it might be important to have a junit 5 example for Scenarioo soon. 

With junit5 integration of scenarioo should be even more elegant.

@ideco and @adiherzog what do you think?

**Comment by bruderol** [comment]
@adiherzog  and @ideco I started to migrate to junit 5 on the feature branch - tests are allready running with junit 5 platform using vintage - but still use junit 4 syntax. Next step will be to migrate to new syntax (should be more or less easy) using jupiter.

Question: what do you think should we make the example junit 5 only or still keep the junit 4 example (e.g. on a special junit4 branch)??

**Comment by bruderol** [comment]
And ... guess what ... there are 'Tag' and 'DisplayName' Annotations that might be interesting for us

**Comment by adiherzog** [comment]
Cool, JUnit 5 looks nice. But I think we should also keep the JUnit 4 example for a while (in parallel), as JUnit 5 adoption is probably not so high yet. Or as an alternative we could just add comments wherever you would do something differently in JUnit 4.

**Comment by ideco** [comment]
+1 for keeping them in parallel (maybe in a separate test folder?)

Also: http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/BeforeAllCallback.html this seems ideal for setting up the scenarioo build folder

**Comment by bruderol** [comment]
@ideco I think BeforeAll is just the same as BeforeClass was in JUnit 4 - so it wont help much to replace the static test setup for all test classes. But I think it's not so bad - it is ok how we solved it in the current example.

@adiherzog and @ideco I agree with your other statements - therefore I propose the following: 
1.  do a special junit4 branch with current version of the example
2. Link from the readme on develop branch to that branch

I not consider both examples in one branch as an option since this makes it more difficult to understand the example when there are both dependencies.

**Comment by bruderol** [comment]
Done, see PR #21 - I close this
