### ISSUE TITLE
Change the default branch to master and leave only pizza-shop in gh-pages

### ISSUE THREAD

**Issue by ideco** [scenarioo/pizza-delivery#6]
Since now we have a master branch, it should also be the main branch of this project. Then we can remove the test code from gh-pages and move the pizza-shop to the root folder.

Also, the links in the read-me should be adapted.

**Comment by ideco** [comment]
@bruderol could you please switch the default branch? I don't have the necessary rights. Afterwards I can provide the rest (also renaming prod to pizza-shop)

**Comment by bruderol** [comment]
@ideco I changed it. Ok?

**Comment by ideco** [comment]
Cool, thanks. Then I will proceed moving out the non-web stuff from gh-pages
