### ISSUE TITLE
Jenkins Build: Make it work for feature branches and pull requests

### ISSUE THREAD

**Issue by bruderol** [scenarioo/pizza-delivery#9]
Accpetance criterias
* If a featurer branch is opened like `feature/{issueNumber}-{description}` and a pull request is opened for such a branch and some changes are pushed to it , then the build will run and report success or failure of verifying it properly to the Pull Request on Github
* verify this works for a failing test
* verify this works for a succesful build

**Comment by ideco** [comment]
Actually I don't think this requires changes to the Jenkinsfile, since its already provided by the Jenkins Github Plugin.

I activated the plugin for the pizza pipeline and it seems to work (e.g. https://github.com/scenarioo/pizza-delivery/pull/11)

**Comment by bruderol** [comment]
@ideco I do not see any build feedback on this mentioned pull request. Do you?? Where?

**Comment by bruderol** [comment]
@ideco See here: https://github.com/scenarioo/scenarioo/blob/427-ConfigurationFileMove/Jenkinsfile

I think the following is missing:
```
properties([
		  pipelineTriggers([
					 [$class: 'GitHubPushTrigger']
		  ])
])
```

**Comment by bruderol** [comment]
@ideco Problem was there was a setting on the jenkins build pipeline to ignore branches that have a pull request open - very useful :roll_eyes: ;-)

**Comment by bruderol** [comment]
There are still problems:
1. The PR reports successful build although the build for the branch failed (see build below): https://github.com/scenarioo/pizza-delivery/pull/12
2. The link to the PR build (that was indeed succesful) is somehow wrong on the PR (see link "Details")
3. The build fails because of unsupported branch name: http://build.scenarioo.org/jenkins/job/pizza-delivery-pipeline/job/feature%252F9-jenkins-github-notifications/2/console

We have to clarify how this was configured for `scenarioo` main repo and do it the same way here.

**Comment by bruderol** [comment]
ok, I tried to configure similar to scenarioo repo

**Comment by bruderol** [comment]
@ideco seems that pushing to github about failure or success works best when only configuring the repo as GitHub (and not as usual Git) in Jenkins config - as done in jenkins config for scenarioo pipeline - now both pipelines are the same and seems to work. 

We could define later to let builds only run for open PRs  - actually I would prefer that - but that would be another story.

**Comment by bruderol** [comment]
@ideco done - I close this, please review and merge https://github.com/scenarioo/pizza-delivery/pull/12
